/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Design System — Material 3 tokens
        "surface-variant": "#e2e2e2",
        "outline": "#916e6f",
        "on-primary-fixed": "#40000c",
        "on-secondary-fixed-variant": "#3631b4",
        "surface-bright": "#f9f9f9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "inverse-primary": "#ffb3b5",
        "outline-variant": "#e6bcbd",
        "secondary": "#4c4aca",
        "surface": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#310048",
        "primary": "#ba0034",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdada",
        "surface-container-high": "#e8e8e8",
        "background": "#f9f9f9",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e2",
        "primary-container": "#e51245",
        "on-primary-fixed-variant": "#920027",
        "on-secondary-fixed": "#0c006a",
        "on-surface-variant": "#5d3f40",
        "secondary-fixed": "#e2dfff",
        "surface-dim": "#dadada",
        "tertiary-container": "#a649d5",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1c",
        "surface-container": "#eeeeee",
        "on-tertiary-container": "#fffbff",
        "surface-tint": "#be0036",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "tertiary": "#8a2bb9",
        "on-primary-container": "#fffbff",
        "surface-container-low": "#f4f3f3",
        "tertiary-fixed-dim": "#e8b3ff",
        "secondary-container": "#6664e4",
        "tertiary-fixed": "#f6d9ff",
        "on-error": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-background": "#1a1c1c",
        "secondary-fixed-dim": "#c2c1ff",
        "on-tertiary-fixed-variant": "#7201a2",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb3b5",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-up': 'slideUp 0.4s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'bar-grow': 'barGrow 0.6s ease-out forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        barGrow: {
          from: { transform: 'scaleY(0)', opacity: '0' },
          to: { transform: 'scaleY(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
